try different wait

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -25,17 +25,21 @@ jobs:
       - checkout
       # Our primary container isn't MYSQL so run a sleep command until it's ready.
       
+      # - run:
+      #     name: Waiting for MySQL to be ready
+      #     command: |
+      #       echo Waiting for MySQL to be ready...
+      #       for i in `seq 1 10`;
+      #       do
+      #         nc -z 127.0.0.1 3306 && echo Success && exit 0
+      #         echo -n .
+      #         sleep 1
+      #       done
+      #       echo Failed waiting for MySQL && exit 1
       - run:
-          name: Waiting for MySQL to be ready
-          command: |
-            echo Waiting for MySQL to be ready...
-            for i in `seq 1 10`;
-            do
-              nc -z 127.0.0.1 3306 && echo Success && exit 0
-              echo -n .
-              sleep 1
-            done
-            echo Failed waiting for MySQL && exit 1
+        name: Wait for Database Connection
+        # preinstalled in circleci/* docker image
+        command: dockerize -wait tcp://localhost:3306 -timeout 1m
       
       # Test MySQL
       - run:
